decoration { 
                    blur { 
                        enabled = true 
                    } 
                } 
                animations { 
                    enabled = true 
                }
                source = /home/felip/.config/hypr/extra/opacity.conf
